# Generated by Django 5.2.3 on 2025-06-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=5, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
