# Generated by Django 5.2.3 on 2025-06-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_currency_created_at_currency_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
    ]
