# Generated by Django 5.2.3 on 2025-06-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_remove_product_unit_and_more'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.ManyToManyField(blank=True, to='units.unit'),
        ),
    ]
