# Generated by Django 5.2.3 on 2025-06-20 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_change_currency', models.BooleanField(default=False)),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
