# Generated by Django 5.2.3 on 2025-06-20 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_currency_options'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='default_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
    ]
