# Generated by Django 5.2.3 on 2025-06-16 21:28

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('domain_name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('heard_from', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('friend', 'Friend / Word of Mouth'), ('radio', 'Radio'), ('tv', 'TV'), ('newspaper', 'Newspaper'), ('flyer', 'Flyer'), ('jshop_website', 'Jshop Website'), ('event', 'Event / Seminar'), ('email', 'Email Campaign'), ('sms', 'SMS'), ('billboard', 'Billboard'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='other', max_length=20, verbose_name='How did you hear about us?')),
                ('agreed_to_terms', models.BooleanField(default=False, help_text='I agree to the General Terms of Use, Merchant Terms of Use & General Privacy Policy of Jshop')),
                ('wants_marketing', models.BooleanField(default=False, help_text="I'd like to receive marketing communication and business tips from Jshop")),
                ('weekly_orders', models.PositiveIntegerField(help_text='How many orders do you get weekly?', verbose_name='Weekly Orders')),
                ('staff_count', models.PositiveIntegerField(help_text='How many staff do you have?', verbose_name='Number of Staff')),
                ('physical_store_count', models.PositiveIntegerField(help_text='How many physical stores do you have?', verbose_name='Number of Physical Stores')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
