# Generated by Django 5.2.3 on 2025-06-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_domain_created_at_domain_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantuserregistry',
            options={'ordering': ('tenant',), 'verbose_name_plural': 'Tenant User Registries'},
        ),
    ]
